version: "3.7"
services: 
 sql-server-db: 
    container-name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
     -"1433:1433"
    enviroment: 
     SA_PASSWORD: "password"
     ACCEPT_EULA: "Y"
    
    